export const db = jest.fn()
export const isInNotebook = jest.fn()
export const saveWord = jest.fn()
export const deleteWord = jest.fn()
export const getWordsByText = jest.fn()
export const getAllWords = jest.fn()
